### PR TITLE
added error ratio to metrics

### PR DESCRIPTION
**Pull request by tperol**
Added Error ratio to list of available metrics in Locust

### CODE REVIEW

**Comment by jgustie** [comment]
Why add this here instead of just making it part of the metric query on the experiment?

I kind of like that these images expose metrics 1-1 with the underlying tool.

**Comment by tperol** [comment]
I agree that it's nice to have only the metrics from the underlying tool. However that means that you cannot optimize for the error_ratio from the `app.yaml` you would have to edit the generated `experiment.yaml`.

**Comment by jgustie** [comment]
You cannot optimize on arbitrary metrics from the application definition (you are limited to "objectives" which are currently resource requests and latency) so no matter what it is going to require manual edits.

We could add an "error rate" objective that is smart enough to use the StormForger `error_ratio` metric or generates the `failure_count/request_count` query for you if you are using Locust.

**Comment by tperol** [comment]
I did not realize that we only had access to `cost` and `latency` in the objectives but i see that here: https://github.com/thestormforge/optimize-controller/blob/1f9ccf2ba4eea94a4d748d19323d925cb0176563/api/apps/v1alpha1/application_defaults.go#L105
Well i think it's worth adding `error_rate` or `error_rate` and pull it directly from stormforger metrics or do the ratio there for locust as you said. I am closing that PR then and we can do it on the controller side.

**Pull request closed without merging**
